from app.application.dtos.auth import (
    ActualizarPerfilRequest,
    CrearDocenteRequest,
    LoginRequest,
    LogoutRequest,
    RefreshRequest,
    TokenResponse,
    UsuarioPublicoDTO,
)
from app.application.dtos.catalogo import (
    ActualizarEventoRequest,
    ActualizarNoticiaRequest,
    ActualizarReporteRequest,
    ArchivoDTO,
    CambiarEstadoReporteRequest,
    CategoriaDTO,
    CrearEventoRequest,
    CrearNoticiaRequest,
    CrearReporteRequest,
    DashboardDTO,
    EventoDTO,
    NoticiaDTO,
    ReporteDTO,
)

__all__ = [
    "ActualizarEventoRequest",
    "ActualizarNoticiaRequest",
    "ActualizarPerfilRequest",
    "ActualizarReporteRequest",
    "ArchivoDTO",
    "CambiarEstadoReporteRequest",
    "CategoriaDTO",
    "CrearDocenteRequest",
    "CrearEventoRequest",
    "CrearNoticiaRequest",
    "CrearReporteRequest",
    "DashboardDTO",
    "EventoDTO",
    "LoginRequest",
    "LogoutRequest",
    "NoticiaDTO",
    "RefreshRequest",
    "ReporteDTO",
    "TokenResponse",
    "UsuarioPublicoDTO",
]
